---
swagger: "2.0"
info:
  description: "This is a sample for swagger-maven-plugin"
  version: "v1"
  title: "Swagger Maven Plugin Sample"
  termsOfService: "http://www.github.com/kongchen/swagger-maven-plugin"
  contact:
    name: "Kong Chen"
    url: "http://kongch.com"
    email: "kongchen@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost"
basePath: "/api"
tags:
- name: "Hello Controller"
schemes:
- "http"
- "https"
paths:
  /api/hello:
    get:
      tags:
      - "Hello Controller"
      operationId: "hello"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            type: "string"
